### ISSUE TITLE
[prettier-plugin-sh] v0.12.0 crashes

### ISSUE THREAD

**Issue by jlarmstrongiv** [rx-ts/prettier#182] opened 2022-06-25 16:35 UTC
0.11.0 runs just fine

Error running prettier update on mac:
```
96841 Bus error: 10
```
Error running prettier check on mac:
```
97549 Bus error: 10
```

Error running check in linux CI:
```
> turbo-monorepo@1.0.0 turbo:prettier:check
> bin/prettier/check
[warn] bin/deepl/check
Error:  bin/docker/run: TypeError: Cannot read properties of undefined (reading 'Col')
Error:      at new ShParseError (/home/ubuntu/actions-runner/_work/turbo-monorepo/turbo-monorepo/node_modules/prettier-plugin-sh/lib/index.cjs:426:25)
Error:      at Object.parse (/home/ubuntu/actions-runner/_work/turbo-monorepo/turbo-monorepo/node_modules/prettier-plugin-sh/lib/index.cjs:445:17)
Error:      at Object.parse (/home/ubuntu/actions-runner/_work/turbo-monorepo/turbo-monorepo/node_modules/prettier/index.js:7334:23)
Error:      at coreFormat (/home/ubuntu/actions-runner/_work/turbo-monorepo/turbo-monorepo/node_modules/prettier/index.js:8645:18)
Error:      at formatWithCursor2 (/home/ubuntu/actions-runner/_work/turbo-monorepo/turbo-monorepo/node_modules/prettier/index.js:8837:18)
Error:      at Object.formatWithCursor (/home/ubuntu/actions-runner/_work/turbo-monorepo/turbo-monorepo/node_modules/prettier/index.js:37229:12)
Error:      at format (/home/ubuntu/actions-runner/_work/turbo-monorepo/turbo-monorepo/node_modules/prettier/cli.js:14748:24)
Error:      at formatFiles2 (/home/ubuntu/actions-runner/_work/turbo-monorepo/turbo-monorepo/node_modules/prettier/cli.js:14860:22)
Error:      at async main (/home/ubuntu/actions-runner/_work/turbo-monorepo/turbo-monorepo/node_modules/prettier/cli.js:15077:5)
Error:      at async Object.run (/home/ubuntu/actions-runner/_work/turbo-monorepo/turbo-monorepo/node_modules/prettier/cli.js:15024:5)
Error:  bin/git/ensure_repository: TypeError: Cannot read properties of undefined (reading 'Col')
Error:      at new ShParseError (/home/ubuntu/actions-runner/_work/turbo-monorepo/turbo-monorepo/node_modules/prettier-plugin-sh/lib/index.cjs:426:25)
Error:      at Object.parse (/home/ubuntu/actions-runner/_work/turbo-monorepo/turbo-monorepo/node_modules/prettier-plugin-sh/lib/index.cjs:445:17)
Error:      at Object.parse (/home/ubuntu/actions-runner/_work/turbo-monorepo/turbo-monorepo/node_modules/prettier/index.js:7334:23)
Error:      at coreFormat (/home/ubuntu/actions-runner/_work/turbo-monorepo/turbo-monorepo/node_modules/prettier/index.js:8645:18)
Error:      at formatWithCursor2 (/home/ubuntu/actions-runner/_work/turbo-monorepo/turbo-monorepo/node_modules/prettier/index.js:8837:18)
Error:      at Object.formatWithCursor (/home/ubuntu/actions-runner/_work/turbo-monorepo/turbo-monorepo/node_modules/prettier/index.js:37229:12)
Error:      at format (/home/ubuntu/actions-runner/_work/turbo-monorepo/turbo-monorepo/node_modules/prettier/cli.js:14748:24)
Error:      at formatFiles2 (/home/ubuntu/actions-runner/_work/turbo-monorepo/turbo-monorepo/node_modules/prettier/cli.js:14860:22)
Error:      at async main (/home/ubuntu/actions-runner/_work/turbo-monorepo/turbo-monorepo/node_modules/prettier/cli.js:15077:5)
Error:      at async Object.run (/home/ubuntu/actions-runner/_work/turbo-monorepo/turbo-monorepo/node_modules/prettier/cli.js:15024:5)
Error:  bin/globals/branch: TypeError: Cannot read properties of undefined (reading 'Col')
Error:      at new ShParseError (/home/ubuntu/actions-runner/_work/turbo-monorepo/turbo-monorepo/node_modules/prettier-plugin-sh/lib/index.cjs:426:25)
Error:      at Object.parse (/home/ubuntu/actions-runner/_work/turbo-monorepo/turbo-monorepo/node_modules/prettier-plugin-sh/lib/index.cjs:445:17)
Error:      at Object.parse (/home/ubuntu/actions-runner/_work/turbo-monorepo/turbo-monorepo/node_modules/prettier/index.js:7334:23)
Error:      at coreFormat (/home/ubuntu/actions-runner/_work/turbo-monorepo/turbo-monorepo/node_modules/prettier/index.js:8645:18)
Error:      at formatWithCursor2 (/home/ubuntu/actions-runner/_work/turbo-monorepo/turbo-monorepo/node_modules/prettier/index.js:8837:18)
Error:      at Object.formatWithCursor (/home/ubuntu/actions-runner/_work/turbo-monorepo/turbo-monorepo/node_modules/prettier/index.js:37229:12)
Error:      at format (/home/ubuntu/actions-runner/_work/turbo-monorepo/turbo-monorepo/node_modules/prettier/cli.js:14748:24)
Error:      at formatFiles2 (/home/ubuntu/actions-runner/_work/turbo-monorepo/turbo-monorepo/node_modules/prettier/cli.js:14860:22)
Error:      at async main (/home/ubuntu/actions-runner/_work/turbo-monorepo/turbo-monorepo/node_modules/prettier/cli.js:15077:5)
Error:      at async Object.run (/home/ubuntu/actions-runner/_work/turbo-monorepo/turbo-monorepo/node_modules/prettier/cli.js:15024:5)
Error:  bin/globals/os: TypeError: Cannot read properties of undefined (reading 'Col')
Error:      at new ShParseError (/home/ubuntu/actions-runner/_work/turbo-monorepo/turbo-monorepo/node_modules/prettier-plugin-sh/lib/index.cjs:426:25)
Error:      at Object.parse (/home/ubuntu/actions-runner/_work/turbo-monorepo/turbo-monorepo/node_modules/prettier-plugin-sh/lib/index.cjs:445:17)
Error:      at Object.parse (/home/ubuntu/actions-runner/_work/turbo-monorepo/turbo-monorepo/node_modules/prettier/index.js:7334:23)
Error:      at coreFormat (/home/ubuntu/actions-runner/_work/turbo-monorepo/turbo-monorepo/node_modules/prettier/index.js:8645:18)
Error:      at formatWithCursor2 (/home/ubuntu/actions-runner/_work/turbo-monorepo/turbo-monorepo/node_modules/prettier/index.js:8837:18)
Error:      at Object.formatWithCursor (/home/ubuntu/actions-runner/_work/turbo-monorepo/turbo-monorepo/node_modules/prettier/index.js:37229:12)
Error:      at format (/home/ubuntu/actions-runner/_work/turbo-monorepo/turbo-monorepo/node_modules/prettier/cli.js:14748:24)
Error:      at formatFiles2 (/home/ubuntu/actions-runner/_work/turbo-monorepo/turbo-monorepo/node_modules/prettier/cli.js:14860:22)
Error:      at async main (/home/ubuntu/actions-runner/_work/turbo-monorepo/turbo-monorepo/node_modules/prettier/cli.js:15077:5)
Error:      at async Object.run (/home/ubuntu/actions-runner/_work/turbo-monorepo/turbo-monorepo/node_modules/prettier/cli.js:15024:5)
Error:  bin/globals/stage: TypeError: Cannot read properties of undefined (reading 'Col')
Error:      at new ShParseError (/home/ubuntu/actions-runner/_work/turbo-monorepo/turbo-monorepo/node_modules/prettier-plugin-sh/lib/index.cjs:426:25)
Error:      at Object.parse (/home/ubuntu/actions-runner/_work/turbo-monorepo/turbo-monorepo/node_modules/prettier-plugin-sh/lib/index.cjs:445:17)
Error:      at Object.parse (/home/ubuntu/actions-runner/_work/turbo-monorepo/turbo-monorepo/node_modules/prettier/index.js:7334:23)
Error:      at coreFormat (/home/ubuntu/actions-runner/_work/turbo-monorepo/turbo-monorepo/node_modules/prettier/index.js:8645:18)
Error:      at formatWithCursor2 (/home/ubuntu/actions-runner/_work/turbo-monorepo/turbo-monorepo/node_modules/prettier/index.js:8837:18)
Error:      at Object.formatWithCursor (/home/ubuntu/actions-runner/_work/turbo-monorepo/turbo-monorepo/node_modules/prettier/index.js:37229:12)
Error:      at format (/home/ubuntu/actions-runner/_work/turbo-monorepo/turbo-monorepo/node_modules/prettier/cli.js:14748:24)
Error:      at formatFiles2 (/home/ubuntu/actions-runner/_work/turbo-monorepo/turbo-monorepo/node_modules/prettier/cli.js:14860:22)
Error:      at async main (/home/ubuntu/actions-runner/_work/turbo-monorepo/turbo-monorepo/node_modules/prettier/cli.js:15077:5)
Error:      at async Object.run (/home/ubuntu/actions-runner/_work/turbo-monorepo/turbo-monorepo/node_modules/prettier/cli.js:15024:5)
[warn] bin/third-party/turbo_install
Error:  bin/third-party/ubuntu-22/packages/autotrace: RuntimeError: memory access out of bounds
Error:      at (runtime.gcBlock).state (wasm://wasm/002c9a4a:wasm-function[161]:0x16d3d)
Error:      at (runtime.gcBlock).findHead (wasm://wasm/002c9a4a:wasm-function[171]:0x172d6)
Error:      at runtime.markRoots (wasm://wasm/002c9a4a:wasm-function[160]:0x16ca4)
Error:      at runtime.alloc (wasm://wasm/002c9a4a:wasm-function[24]:0x166b)
Error:      at github.com/rx-ts/sh-syntax/processor.Parse (wasm://wasm/002c9a4a:wasm-function[641]:0x8c4ee)
Error:      at process (wasm://wasm/002c9a4a:wasm-function[652]:0x90706)
Error:      at process.command_export (wasm://wasm/002c9a4a:wasm-function[670]:0x95e4e)
Error:      at file:///home/ubuntu/actions-runner/_work/turbo-monorepo/turbo-monorepo/node_modules/sh-syntax/lib/processor.js:48:35
Error:      at Generator.next (<anonymous>)
Error:      at fulfilled (/home/ubuntu/actions-runner/_work/turbo-monorepo/turbo-monorepo/node_modules/tslib/tslib.js:115:62)
[warn] Code style issues found in 2 files. Forgot to run Prettier?
Error: Process completed with exit code 2.
```

**Comment by JounQin** [comment] 2022-06-25 16:36
Sorry about this, can you provide a runnable reproduction?

**Comment by jlarmstrongiv** [comment] 2022-06-25 16:52
I emailed you a zip with a simplified reproduction 👍

**Comment by JounQin** [comment] 2022-06-25 17:09
```log
npmR turbo:prettier:check:all   

> turbo-monorepo@1.0.0 turbo:prettier:check:all
> npm run turbo:prettier:check


> turbo-monorepo@1.0.0 turbo:prettier:check
> bin/prettier/check

realpath: illegal option -- s
usage: realpath [-q] [path ...]
bin/prettier/check: line 4: ./../functions/monorepo_path: No such file or directory
```

No idea what is happening, your reproduction is too huge.

**Comment by jlarmstrongiv** [comment] 2022-06-25 17:14
Try running `npx prettier "**/*" --ignore-unknown --loglevel warn --check` ?

```
bus error
```

**Comment by JounQin** [comment] 2022-06-25 17:17
Ok, I'll try to find out what is going on tomorrow.

**Comment by stefanks** [comment] 2022-06-25 23:13
A new crash as well. Here is my log:
```
[error] Cannot find module 'node:path'

[error] Require stack:

[error] - /usr/local/lib/node_modules/prettier-plugin-sh/lib/index.cjs

[error] - /usr/local/lib/node_modules/prettier/index.js

[error] - /usr/local/lib/node_modules/prettier/cli.js

[error] - /usr/local/lib/node_modules/prettier/bin-prettier.js

npm ERR! code 1

npm ERR! path /app
```

**Comment by JounQin** [comment] 2022-06-26 00:15
@stefanks The package requires Node.js `^12.20 || ^14.18.0 || >=16.0.0` now, see  https://2ality.com/2021/12/node-protocol-imports.html for more details.

**Comment by JounQin** [comment] 2022-06-26 02:21
@jlarmstrongiv I think this because you shellscript will produce a temporary shellscript? This should, can be improved in [sh-syntax](https://github.com/rx-ts/sh-syntax), working on fix.

**Comment by JounQin** [comment] 2022-06-26 02:54
bin/docker/run/xx/tmp/npx-1656211959201.sh

This is a `virtual` filename...

**Comment by JounQin** [comment] 2022-06-26 03:06
<img width="903" alt="image" src="https://user-images.githubusercontent.com/8336744/175797598-dc4628e3-52cf-4bc8-9c08-c7f79f1f7c36.png">

Sorry I'm not sure where `/Users/JounQin/tmp/npx-1656212569917.sh` comes from, and it is not even passed into `prettier-plugin-sh`'s options.

I think I'm just wasting time on this, please provide more useful info. I don't understand how's your `prettier` script working.

**Comment by JounQin** [comment] 2022-06-26 03:22
> TypeError: Cannot read properties of undefined (reading 'Col')

This error has been fixed in prettier-plugin-sh v0.12.1, please provide more specific and reduced reproduction next time.

> I think I'm just wasting time on this, please provide more useful info. I don't understand how's your prettier script working.

**Comment by JounQin** [comment] 2022-06-26 03:26
Besides, I have different format error from `bin/deepl/check` on different OSes:

```log
# macOs
reached EOF without matching <( with )

# Ubuntu
"foo(" must be followed by )
```

**Comment by jlarmstrongiv** [comment] 2022-06-26 14:25
What a strange bug!

> I think this because you shellscript will produce a temporary shellscript?

Interesting!  The only temporary shell scripts I know of are generated from [husky](https://www.npmjs.com/package/husky) under `.husky/_`.  But, that should have been removed from the reproduction.  

These are all files that live in the project’s bin folder.  A series of scripts that help me run and automate common tasks:
```
bin/deepl/check
bin/docker/run
bin/git/ensure_repository
bin/globals/branch
bin/globals/os
bin/globals/stage
bin/third-party/turbo_install
bin/third-party/ubuntu-22/packages/autotrace
```

While the `bin/docker/run` may seem like a virtual path, it’s a bash script to help me spin up a docker container and clean it up after I exit.

> bin/docker/run/xx/tmp/npx-1656211959201.sh
> /Users/JounQin/tmp/npx-1656212569917.sh

Now these paths are very weird!!  

As you described, that file path isn’t passed into the options, so I have no idea where it would be coming from.  I’m glad you were able to find that name though!  I never would’ve found that type of file otherwise.  I checked for similar npx files in tmp, but couldn’t find any.  

Unfortunately, I am still receiving the error `50461 Bus error: 10` on the latest update `0.12.2`.

Is there anyway to ignore that type of file to prevent crashes?  I think https://github.com/rx-ts/sh-syntax/pull/37/files could be a good solution

---

> different format error from bin/deepl/check on different OSes

That’s interesting.  Is this format accepted by the plugin?

```bash
<(git --no-pager diff --cached --name-only --diff-filter='ACMRTUXB' -- 'packages/translations/en'; echo)
```

I originally changed it to multiline due to suggestions from v0.11.0 of the plugin.  Strange that it’s a different error per os.

---

I really appreciate your help with this bug @JounQin can we re-open this issue?

> I think I'm just wasting time on this, please provide more useful info

I tried running prettier in debug mode, but that didn’t have anything useful.  I am glad you can were able to see the `bus error` by running `npx prettier "**/*" --ignore-unknown --loglevel warn --check`.  But, I’m very sorry I can’t find more details on it.  Do you accept donations or have a favorite non-profit?

**Comment by JounQin** [comment] 2022-06-26 14:54
> Unfortunately, I am still receiving the error 50461 Bus error: 10 on the latest update 0.12.2.

I can only see the log with `--check`, `prettier --write` should just ignore any error

> Is there anyway to ignore that type of file to prevent crashes? I think https://github.com/rx-ts/sh-syntax/pull/37/files could be a good solution

I tried that PR locally failed, you could try it https://ci.codesandbox.io/status/rx-ts/sh-syntax/pr/37/builds/265257

> That’s interesting. Is this format accepted by the plugin?

This plugin use [sh-syntax](https://github.com/rx-ts/sh-syntax), which uses [mvdan/sh](https://github.com/mvdan/sh) under the hood, maybe you can try https://github.com/mvdan/sh#shfmt to check whether it's a bug of this plugin or the upstream instead.

> I really appreciate your help with this bug @JounQin can we re-open this issue?

Reopen doesn't mean I can get more info from the reproduction, I'm glad to reopen if you can help me to understand where's the `virtual` file path from. I'm not familiar with your project and shellscripts.

> Do you accept donations or have a favorite non-profit?

I'm glad if you want to donate, the link is always there on the project homepage as GitHub sponsor, that would be appreciated, but it doesn't change the fact I can't get much useful info from your reproduction, as you can see I've added a test case for your reproduction file: https://github.com/rx-ts/prettier/blob/master/packages/sh/test/fixtures/182-diff-os, you can try to clone and run `yarn test` to see what error is thrown first.

https://github.com/rx-ts/prettier/blob/master/packages/sh/test/fixture.spec.ts#L41

**Comment by jlarmstrongiv** [comment] 2022-06-26 16:13
> I'm glad to reopen if you can help me to understand where's the virtual file path from

I’m inclined to think that’s a bug with v0.12.x, as it did not occur with v0.11.0.  

The command `npx prettier "**/*" --ignore-unknown --loglevel warn --check` should only include project files, so I am very confused why it would be detecting temporary paths or paths that don’t exist at all.  I can always ignore specific bash scripts, but those paths erroring with `Bus error` prevent me from using prettier-plugin-sh v0.12.0 and beyond.

**Comment by JounQin** [comment] 2022-06-26 16:40
> I’m inclined to think that’s a bug with v0.12.x, as it did not occur with v0.11.0.

Yeah, I understand this.

> so I am very confused why it would be detecting temporary paths or paths that don’t exist at all.

From what I understand, it could be related to turbo's behavior.

Can you check it's document or raise a related issue there?

I'll reopen this issue for now, but I need more time to dig deeper or info from other views.

**Comment by JounQin** [comment] 2022-06-27 02:54
I just had an idea that it could be related to https://github.com/rx-ts/sh-syntax/blob/main/main.go#L119

**Comment by JounQin** [comment] 2022-06-27 03:08
@jlarmstrongiv Please help to try:

```jsonc
{
  // package.json
  "overrides": {
    "sh-syntax": "https://pkg.csb.dev/rx-ts/sh-syntax/commit/5ef14831/sh-syntax"
  }
}
```

**Comment by JounQin** [comment] 2022-06-27 05:16
@mvdan Do you have any idea what may be happening, causing:

```
/xxx/tmp/npx-1656306571717.sh: line 2:  5865 Bus error: 10           prettier '**/*' --ignore-unknown --loglevel warn --check
```

**Comment by JounQin** [comment] 2022-06-27 05:35
Fine, https://github.com/rx-ts/sh-syntax/pull/42 seems did the trick, although I don't understand why.

```log
[warn] bin/docker/run
[error] bin/globals/branch: SyntaxError: offset is out of bounds
[error]     at Object.parse (/Users/JounQin/Workspaces/Local/sh-plugin-error-reproduction/node_modules/prettier-plugin-sh/lib/index.cjs:443:17)
[error]     at Object.parse (/Users/JounQin/Workspaces/Local/sh-plugin-error-reproduction/node_modules/prettier/index.js:7334:23)
[error]     at coreFormat (/Users/JounQin/Workspaces/Local/sh-plugin-error-reproduction/node_modules/prettier/index.js:8645:18)
[error]     at formatWithCursor2 (/Users/JounQin/Workspaces/Local/sh-plugin-error-reproduction/node_modules/prettier/index.js:8837:18)
[error]     at Object.formatWithCursor (/Users/JounQin/Workspaces/Local/sh-plugin-error-reproduction/node_modules/prettier/index.js:37229:12)
[error]     at format (/Users/JounQin/Workspaces/Local/sh-plugin-error-reproduction/node_modules/prettier/cli.js:14748:24)
[error]     at formatFiles2 (/Users/JounQin/Workspaces/Local/sh-plugin-error-reproduction/node_modules/prettier/cli.js:14860:22)
[error]     at async main (/Users/JounQin/Workspaces/Local/sh-plugin-error-reproduction/node_modules/prettier/cli.js:15077:5)
[error]     at async Object.run (/Users/JounQin/Workspaces/Local/sh-plugin-error-reproduction/node_modules/prettier/cli.js:15024:5)
[error] bin/globals/os: SyntaxError: reached EOF without closing quote "
[error]   38 | echo "$os" >| "$os_path"
[error]   39 |
[error] > 40 | echo "$os"
[error]      |          ^
[error]   41 |
[error] bin/globals/stage: SyntaxError: offset is out of bounds
[error]     at Object.parse (/Users/JounQin/Workspaces/Local/sh-plugin-error-reproduction/node_modules/prettier-plugin-sh/lib/index.cjs:443:17)
[error]     at Object.parse (/Users/JounQin/Workspaces/Local/sh-plugin-error-reproduction/node_modules/prettier/index.js:7334:23)
[error]     at coreFormat (/Users/JounQin/Workspaces/Local/sh-plugin-error-reproduction/node_modules/prettier/index.js:8645:18)
[error]     at formatWithCursor2 (/Users/JounQin/Workspaces/Local/sh-plugin-error-reproduction/node_modules/prettier/index.js:8837:18)
[error]     at Object.formatWithCursor (/Users/JounQin/Workspaces/Local/sh-plugin-error-reproduction/node_modules/prettier/index.js:37229:12)
[error]     at format (/Users/JounQin/Workspaces/Local/sh-plugin-error-reproduction/node_modules/prettier/cli.js:14748:24)
[error]     at formatFiles2 (/Users/JounQin/Workspaces/Local/sh-plugin-error-reproduction/node_modules/prettier/cli.js:14860:22)
[error]     at async main (/Users/JounQin/Workspaces/Local/sh-plugin-error-reproduction/node_modules/prettier/cli.js:15077:5)
[error]     at async Object.run (/Users/JounQin/Workspaces/Local/sh-plugin-error-reproduction/node_modules/prettier/cli.js:15024:5)
[error] bin/third-party/turbo_install: SyntaxError: case statement must end with "esac"
[error] 
[error] bin/third-party/ubuntu-22/packages/doppler: SyntaxError: a command can only contain words and redirects; encountered )
[error]   28 |     echo "deb https://packages.doppler.com/public/cli/deb/debian any-version main" | sudo tee /etc/apt/sources.list.d/doppler-cli.list
[error]   29 |     sudo apt-get update
[error] > 30 |     sudo apt-get install -y doppler
[error]      |                         ^
[error]   31 | fi
[error]   32 |
[warn] Code style issues found in the above file. Forgot to run Prettier?
```

For `offset is out of bounds`, I can reproduce it easily with `npx prettier bin/globals/stage`, will track it in a sperate issue instead.

**Closed by JounQin** 2022-06-27 05:35 UTC

**Comment by jlarmstrongiv** [comment] 2022-06-27 11:35
Awesome 😄 

The good news is that I can now see the error from prettier:

```
[error] bin/deepl/check: SyntaxError: offset is out of bounds
```

Interesting that it occurs in a different file, but hopefully it should be fixed by https://github.com/rx-ts/sh-syntax/issues/45 too 

The bad news is that I’m still receiving the `bus error` in v0.12.3:

```
[error]     at async Object.run (/Users/user/Desktop/monorepos/turbo-monorepo/node_modules/prettier/cli.js:15024:5)
bin/prettier/check: line 18: 23919 Bus error: 10           npx prettier "${ignore_globs[@]:?}" "**/*" --ignore-path="$monorepo_path/.gitignore" --ignore-unknown --loglevel warn --check
```

But, if there’s no `bus error` when all the tests pass with an 0 exit code, then that’s great 👍

---

> From what I understand, it could be related to turbo's behavior.
> Can you check its document or raise a related issue there?

- I [checked](https://github.com/vercel/turborepo/search?q=prettier&type=issues) turborepo for similar reported errors, but didn’t find any.
- I checked, and ensured that I only upgraded `prettier-plugin-sh`, nothing else (including `turbo`)
- I checked the turbo cache for matching paths, but didn’t find any (`.turbo`)
- I ensured that I am not running turbo in these examples (while the command may have been turbo:prettier:check:all, that actually short-circuits to just running prettier in the root, similar to `npx prettier "**/*" --ignore-unknown --loglevel warn --check`)

While turbo has caused problems in the past and I’ve been wrong before, I don’t think it’s turbo this time

---

> I'm going to sleep now, good day.

No rush, just as you’re able 😄 Thank you very much for your help resolving this issue @JounQin I really appreciate it.  I think we’re getting close 🚀

**Comment by JounQin** [comment] 2022-06-28 14:58
Hi, I've decided to revert to use `mvdan-sh` for now, but at least we have more test cases for `sh-syntax`...

**Comment by jlarmstrongiv** [comment] 2022-06-28 15:55
@JounQin can confirm that reverting and using v0.12.4 works 👍 thanks again for your help and patience.  `prettier-plugin-sh` is awesome 🚀
